# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Users.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bUsers.proto\x12\x05users\"2\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"\x10\n\x0eGetUserRequest\"-\n\x0fGetUserResponse\x12\x1a\n\x05users\x18\x01 \x03(\x0b\x32\x0b.users.User\".\n\x10SendDataToServer\x12\x1a\n\x05users\x18\x01 \x01(\x0b\x32\x0b.users.User2\x8b\x01\n\rUserOperation\x12;\n\x08GetUsers\x12\x15.users.GetUserRequest\x1a\x16.users.GetUserResponse\"\x00\x12=\n\x08SendData\x12\x17.users.SendDataToServer\x1a\x16.users.GetUserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=22
  _globals['_USER']._serialized_end=72
  _globals['_GETUSERREQUEST']._serialized_start=74
  _globals['_GETUSERREQUEST']._serialized_end=90
  _globals['_GETUSERRESPONSE']._serialized_start=92
  _globals['_GETUSERRESPONSE']._serialized_end=137
  _globals['_SENDDATATOSERVER']._serialized_start=139
  _globals['_SENDDATATOSERVER']._serialized_end=185
  _globals['_USEROPERATION']._serialized_start=188
  _globals['_USEROPERATION']._serialized_end=327
# @@protoc_insertion_point(module_scope)
